# Generated by Django 2.2.6 on 2019-12-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='gift',
            name='bought',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gift',
            name='boughtBy_1',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='gift',
            name='boughtBy_2',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='gift',
            name='boughtBy_3',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='gift',
            name='boughtBy_4',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='gift',
            name='boughtBy_5',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='gift',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gift',
            name='costPayed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gift',
            name='picture',
            field=models.CharField(default='anka.jpg', max_length=30),
        ),
    ]
