# Generated by Django 2.2.6 on 2019-12-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20191214_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='picture',
            field=models.CharField(default='img/anka.jpg', max_length=30),
        ),
    ]
